-- Execute este arquivo no SQL Editor de um projeto novo no Supabase.

create table public.profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null check (char_length(display_name) between 2 and 40),
  avatar_key text not null default 'classic-ball'
    check (avatar_key in (
      'classic-ball',
      'golden-cup',
      'goalkeeper',
      'football-boot',
      'supporter-horn',
      'stadium-drum',
      'goal-net',
      'brazil',
      'argentina-ten',
      'portugal-seven',
      'penguin-striker',
      'var-alien',
      'capybara-fan',
      'ball-wizard',
      'angry-referee'
    )),
  is_admin boolean not null default false,
  created_at timestamptz not null default now()
);

create table public.matches (
  id bigint generated by default as identity primary key,
  match_number smallint not null unique check (match_number between 1 and 104),
  home_team text not null,
  away_team text not null,
  home_flag text not null default '⚽',
  away_flag text not null default '⚽',
  stage text not null,
  kickoff_at timestamptz not null,
  venue text,
  status text not null default 'scheduled'
    check (status in ('scheduled', 'finished')),
  home_score smallint check (home_score between 0 and 99),
  away_score smallint check (away_score between 0 and 99),
  created_at timestamptz not null default now(),
  constraint finished_match_has_score check (
    status <> 'finished' or (home_score is not null and away_score is not null)
  )
);

create table public.predictions (
  user_id uuid not null references public.profiles(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  home_score smallint not null check (home_score between 0 and 99),
  away_score smallint not null check (away_score between 0 and 99),
  points smallint check (points between 0 and 7),
  updated_at timestamptz not null default now(),
  primary key (user_id, match_id)
);

create table public.ranking_movements (
  user_id uuid primary key references public.profiles(id) on delete cascade,
  previous_position integer not null check (previous_position > 0),
  current_position integer not null check (current_position > 0),
  updated_at timestamptz not null default now()
);

create table public.oracle_predictions (
  user_id uuid not null references public.profiles(id) on delete cascade,
  match_id bigint not null references public.matches(id) on delete cascade,
  pick text not null check (pick in ('home', 'draw', 'away')),
  created_at timestamptz not null default now(),
  primary key (user_id, match_id)
);

create index predictions_match_id_idx on public.predictions(match_id);
create index oracle_predictions_match_id_idx on public.oracle_predictions(match_id);
create index matches_kickoff_at_idx on public.matches(kickoff_at);
create unique index profiles_username_idx
  on public.profiles (
    regexp_replace(lower(trim(display_name)), '[[:space:]]+', '_', 'g')
  );

create or replace function public.handle_new_user()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  insert into public.profiles (id, display_name)
  values (
    new.id,
    coalesce(nullif(trim(new.raw_user_meta_data ->> 'display_name'), ''), 'Participante')
  );
  return new;
end;
$$;

create trigger on_auth_user_created
  after insert on auth.users
  for each row execute procedure public.handle_new_user();

create or replace function public.is_admin()
returns boolean
language sql
stable
security definer set search_path = ''
as $$
  select coalesce(
    (select is_admin from public.profiles where id = auth.uid()),
    false
  );
$$;

create or replace function public.update_username(new_username text)
returns text
language plpgsql
security definer set search_path = ''
as $$
declare
  normalized_username text;
  clean_username text;
  technical_email text;
begin
  if auth.uid() is null then
    raise exception 'Usuário não autenticado.';
  end if;

  clean_username := trim(new_username);
  normalized_username := regexp_replace(
    lower(clean_username),
    '[[:space:]]+',
    '_',
    'g'
  );

  if normalized_username !~ '^[a-z0-9][a-z0-9._-]{2,23}$' then
    raise exception 'Use de 3 a 24 caracteres: letras sem acento, números, espaços, ponto, hífen ou sublinhado.';
  end if;

  if exists (
    select 1
    from public.profiles
    where id <> auth.uid()
      and regexp_replace(
        lower(trim(display_name)),
        '[[:space:]]+',
        '_',
        'g'
      ) = normalized_username
  ) then
    raise exception 'Este username já está em uso.';
  end if;

  technical_email := normalized_username || '@bolasso.invalid';

  update public.profiles
  set display_name = clean_username
  where id = auth.uid();

  update auth.users
  set email = technical_email,
      raw_user_meta_data = jsonb_set(
        coalesce(raw_user_meta_data, '{}'::jsonb),
        '{display_name}',
        to_jsonb(clean_username)
      ),
      updated_at = now()
  where id = auth.uid();

  update auth.identities
  set identity_data = jsonb_set(
    identity_data,
    '{email}',
    to_jsonb(technical_email)
  ),
      updated_at = now()
  where user_id = auth.uid()
    and provider = 'email';

  return clean_username;
end;
$$;

create or replace function public.update_profile_avatar(new_avatar_key text)
returns text
language plpgsql
security definer set search_path = ''
as $$
begin
  if auth.uid() is null then
    raise exception 'Usuário não autenticado.';
  end if;

  if new_avatar_key not in (
    'classic-ball',
    'golden-cup',
    'goalkeeper',
    'football-boot',
    'supporter-horn',
    'stadium-drum',
    'goal-net',
    'brazil',
    'argentina-ten',
    'portugal-seven',
    'penguin-striker',
    'var-alien',
    'capybara-fan',
    'ball-wizard',
    'angry-referee'
  ) then
    raise exception 'Imagem de perfil inválida.';
  end if;

  update public.profiles
  set avatar_key = new_avatar_key
  where id = auth.uid();

  return new_avatar_key;
end;
$$;

create or replace function public.can_edit_prediction(target_match_id bigint)
returns boolean
language sql
stable
security definer set search_path = ''
as $$
  select exists (
    select 1
    from public.matches
    where id = target_match_id
      and status = 'scheduled'
      and kickoff_at - interval '5 minutes' > now()
  );
$$;

create or replace function public.get_oracle_prediction(target_match_id bigint)
returns table (
  match_id bigint,
  pick text,
  created_at timestamptz
)
language plpgsql
security definer set search_path = ''
as $$
declare
  selected_pick text;
begin
  if auth.uid() is null then
    raise exception 'Usuário não autenticado.';
  end if;

  if not exists (
    select 1 from public.matches where id = target_match_id
  ) then
    raise exception 'Jogo não encontrado.';
  end if;

  selected_pick := (
    array['home', 'draw', 'away']
  )[1 + floor(random() * 3)::integer];

  insert into public.oracle_predictions (user_id, match_id, pick)
  values (auth.uid(), target_match_id, selected_pick)
  on conflict (user_id, match_id) do nothing;

  return query
  select
    oracle_predictions.match_id,
    oracle_predictions.pick,
    oracle_predictions.created_at
  from public.oracle_predictions
  where oracle_predictions.user_id = auth.uid()
    and oracle_predictions.match_id = target_match_id;
end;
$$;

create or replace function public.get_participant_predictions(
  target_user_id uuid
)
returns table (
  match_id bigint,
  match_number smallint,
  home_team text,
  away_team text,
  home_flag text,
  away_flag text,
  kickoff_at timestamptz,
  status text,
  final_home_score smallint,
  final_away_score smallint,
  predicted_home_score smallint,
  predicted_away_score smallint,
  points smallint
)
language sql
stable
security definer set search_path = ''
as $$
  select
    m.id,
    m.match_number,
    m.home_team,
    m.away_team,
    m.home_flag,
    m.away_flag,
    m.kickoff_at,
    m.status,
    m.home_score,
    m.away_score,
    pr.home_score,
    pr.away_score,
    pr.points
  from public.matches m
  join public.predictions pr on pr.match_id = m.id
  where pr.user_id = target_user_id
    and m.kickoff_at - interval '5 minutes' <= now()
  order by m.kickoff_at desc;
$$;

create or replace function public.protect_prediction()
returns trigger
language plpgsql
security definer set search_path = ''
as $$
begin
  new.updated_at := now();

  if tg_op = 'INSERT' then
    new.points := null;
  elsif not public.is_admin() then
    new.points := old.points;
  end if;

  return new;
end;
$$;

create trigger protect_prediction_values
  before insert or update on public.predictions
  for each row execute procedure public.protect_prediction();

create or replace function public.calculate_points(
  predicted_home integer,
  predicted_away integer,
  final_home integer,
  final_away integer
)
returns integer
language plpgsql
immutable
as $$
declare
  outcome_points integer := 0;
  one_score_point integer := 0;
begin
  if predicted_home = final_home and predicted_away = final_away then
    return 7;
  end if;

  if sign(predicted_home - predicted_away) = sign(final_home - final_away) then
    outcome_points := 3;
  end if;

  if predicted_home = final_home or predicted_away = final_away then
    one_score_point := 1;
  end if;

  if outcome_points = 3 and one_score_point = 1 then
    return 5;
  end if;

  return outcome_points + one_score_point;
end;
$$;

create or replace function public.refresh_ranking_movements()
returns void
language plpgsql
security definer set search_path = ''
as $$
begin
  with totals as (
    select
      p.id as user_id,
      p.display_name,
      coalesce(sum(pr.points), 0)::bigint as total_points,
      count(*) filter (where pr.points = 7)::bigint as exact_scores,
      count(*) filter (where pr.points = 5)::bigint as five_point_scores,
      count(*) filter (where pr.points = 3)::bigint as three_point_scores,
      count(*) filter (where pr.points = 1)::bigint as one_point_scores
    from public.profiles p
    left join public.predictions pr on pr.user_id = p.id
    group by p.id, p.display_name
  ),
  ranked as (
    select
      user_id,
      rank() over (
        order by
          total_points desc,
          exact_scores desc,
          five_point_scores desc,
          three_point_scores desc,
          one_point_scores desc
      )::integer as ranking_position
    from totals
  )
  insert into public.ranking_movements (
    user_id,
    previous_position,
    current_position,
    updated_at
  )
  select
    ranked.user_id,
    coalesce(movements.current_position, ranked.ranking_position),
    ranked.ranking_position,
    now()
  from ranked
  left join public.ranking_movements movements
    on movements.user_id = ranked.user_id
  on conflict (user_id) do update
  set previous_position = public.ranking_movements.current_position,
      current_position = excluded.current_position,
      updated_at = excluded.updated_at;
end;
$$;

create or replace function public.finish_match(
  target_match_id bigint,
  final_home_score integer,
  final_away_score integer
)
returns void
language plpgsql
security definer set search_path = ''
as $$
begin
  if not public.is_admin() then
    raise exception 'Apenas administradores podem publicar resultados.';
  end if;

  if final_home_score not between 0 and 99
    or final_away_score not between 0 and 99 then
    raise exception 'Placar inválido.';
  end if;

  update public.matches
  set home_score = final_home_score,
      away_score = final_away_score,
      status = 'finished'
  where id = target_match_id
    and kickoff_at <= now();

  if not found then
    raise exception 'O jogo ainda não começou ou não foi encontrado.';
  end if;

  update public.predictions
  set points = public.calculate_points(
    home_score,
    away_score,
    final_home_score,
    final_away_score
  )
  where match_id = target_match_id;

  perform public.refresh_ranking_movements();
end;
$$;

create or replace function public.get_ranking()
returns table (
  user_id uuid,
  display_name text,
  avatar_key text,
  ranking_position integer,
  position_change integer,
  is_tied boolean,
  total_points bigint,
  exact_scores bigint,
  five_point_scores bigint,
  three_point_scores bigint,
  one_point_scores bigint,
  predictions_count bigint
)
language sql
stable
security definer set search_path = ''
as $$
  with totals as (
    select
      p.id as user_id,
      p.display_name,
      p.avatar_key,
      coalesce(sum(pr.points), 0)::bigint as total_points,
      count(*) filter (where pr.points = 7)::bigint as exact_scores,
      count(*) filter (where pr.points = 5)::bigint as five_point_scores,
      count(*) filter (where pr.points = 3)::bigint as three_point_scores,
      count(*) filter (where pr.points = 1)::bigint as one_point_scores,
      count(pr.match_id)::bigint as predictions_count
    from public.profiles p
    left join public.predictions pr on pr.user_id = p.id
    group by p.id, p.display_name, p.avatar_key
  ),
  ranked as (
    select
      totals.*,
      rank() over (
        order by
          total_points desc,
          exact_scores desc,
          five_point_scores desc,
          three_point_scores desc,
          one_point_scores desc
      )::integer as ranking_position,
      count(*) over (
        partition by
          total_points,
          exact_scores,
          five_point_scores,
          three_point_scores,
          one_point_scores
      ) > 1 as is_tied
    from totals
  )
  select
    ranked.user_id,
    ranked.display_name,
    ranked.avatar_key,
    ranked.ranking_position,
    coalesce(
      movements.previous_position - movements.current_position,
      0
    )::integer as position_change,
    ranked.is_tied,
    ranked.total_points,
    ranked.exact_scores,
    ranked.five_point_scores,
    ranked.three_point_scores,
    ranked.one_point_scores,
    ranked.predictions_count
  from ranked
  left join public.ranking_movements movements
    on movements.user_id = ranked.user_id
  order by ranked.ranking_position, ranked.display_name asc;
$$;

alter table public.profiles enable row level security;
alter table public.matches enable row level security;
alter table public.predictions enable row level security;
alter table public.ranking_movements enable row level security;
alter table public.oracle_predictions enable row level security;

create policy "Authenticated users can see profiles"
  on public.profiles for select
  to authenticated
  using (true);

create policy "Authenticated users can see matches"
  on public.matches for select
  to authenticated
  using (true);

create policy "Admins can create matches"
  on public.matches for insert
  to authenticated
  with check (public.is_admin());

create policy "Admins can update matches"
  on public.matches for update
  to authenticated
  using (public.is_admin())
  with check (public.is_admin());

create policy "Users can see their predictions"
  on public.predictions for select
  to authenticated
  using (auth.uid() = user_id or public.is_admin());

create policy "Users can create predictions before kickoff"
  on public.predictions for insert
  to authenticated
  with check (
    auth.uid() = user_id
    and public.can_edit_prediction(match_id)
  );

create policy "Users can update predictions before kickoff"
  on public.predictions for update
  to authenticated
  using (
    auth.uid() = user_id
    and public.can_edit_prediction(match_id)
  )
  with check (
    auth.uid() = user_id
    and public.can_edit_prediction(match_id)
);

create policy "Users can see their oracle predictions"
  on public.oracle_predictions for select
  to authenticated
  using (auth.uid() = user_id);

revoke all on function public.finish_match(bigint, integer, integer) from public;
grant execute on function public.finish_match(bigint, integer, integer) to authenticated;
revoke all on function public.refresh_ranking_movements() from public;
revoke all on function public.refresh_ranking_movements() from authenticated;
revoke all on function public.get_oracle_prediction(bigint) from public;
grant execute on function public.get_oracle_prediction(bigint) to authenticated;
revoke all on function public.get_ranking() from public;
grant execute on function public.get_ranking() to authenticated;
revoke all on function public.update_username(text) from public;
grant execute on function public.update_username(text) to authenticated;
revoke all on function public.update_profile_avatar(text) from public;
grant execute on function public.update_profile_avatar(text) to authenticated;
revoke all on function public.get_participant_predictions(uuid) from public;
grant execute on function public.get_participant_predictions(uuid) to authenticated;

alter publication supabase_realtime add table public.profiles;
alter publication supabase_realtime add table public.matches;
alter publication supabase_realtime add table public.predictions;

-- Depois de criar sua própria conta, torne-a administradora pelo username:
-- update public.profiles
-- set is_admin = true
-- where lower(display_name) = lower('seu_username');

-- Fase de grupos oficial. Os horários estão escritos em Abu Dhabi (UTC+4).
insert into public.matches
  (match_number, home_team, away_team, home_flag, away_flag, stage, kickoff_at, venue)
values
  (1, 'México', 'África do Sul', '🇲🇽', '🇿🇦', 'Grupo A', '2026-06-11 23:00:00+04', 'Estadio Banorte · Mexico City'),
  (2, 'Coreia do Sul', 'Tchéquia', '🇰🇷', '🇨🇿', 'Grupo A', '2026-06-12 06:00:00+04', 'Estadio Akron · Guadalajara'),
  (3, 'Canadá', 'Bósnia e Herzegovina', '🇨🇦', '🇧🇦', 'Grupo B', '2026-06-12 23:00:00+04', 'BMO Field · Toronto'),
  (4, 'Estados Unidos', 'Paraguai', '🇺🇸', '🇵🇾', 'Grupo D', '2026-06-13 05:00:00+04', 'SoFi Stadium · Inglewood, California'),
  (5, 'Catar', 'Suíça', '🇶🇦', '🇨🇭', 'Grupo B', '2026-06-13 23:00:00+04', 'Levi''s Stadium · Santa Clara, California'),
  (6, 'Brasil', 'Marrocos', '🇧🇷', '🇲🇦', 'Grupo C', '2026-06-14 02:00:00+04', 'MetLife Stadium · East Rutherford, New Jersey'),
  (7, 'Haiti', 'Escócia', '🇭🇹', '🏴', 'Grupo C', '2026-06-14 05:00:00+04', 'Gillette Stadium · Foxborough, Massachusetts'),
  (8, 'Austrália', 'Turquia', '🇦🇺', '🇹🇷', 'Grupo D', '2026-06-14 08:00:00+04', 'BC Place · Vancouver'),
  (9, 'Alemanha', 'Curaçao', '🇩🇪', '🇨🇼', 'Grupo E', '2026-06-14 21:00:00+04', 'NRG Stadium · Houston, Texas'),
  (10, 'Países Baixos', 'Japão', '🇳🇱', '🇯🇵', 'Grupo F', '2026-06-15 00:00:00+04', 'AT&T Stadium · Arlington, Texas'),
  (11, 'Costa do Marfim', 'Equador', '🇨🇮', '🇪🇨', 'Grupo E', '2026-06-15 03:00:00+04', 'Lincoln Financial Field · Philadelphia, Pennsylvania'),
  (12, 'Suécia', 'Tunísia', '🇸🇪', '🇹🇳', 'Grupo F', '2026-06-15 06:00:00+04', 'Estadio BBVA · Guadalupe'),
  (13, 'Espanha', 'Cabo Verde', '🇪🇸', '🇨🇻', 'Grupo H', '2026-06-15 20:00:00+04', 'Mercedes-Benz Stadium · Atlanta, Georgia'),
  (14, 'Bélgica', 'Egito', '🇧🇪', '🇪🇬', 'Grupo G', '2026-06-15 23:00:00+04', 'Lumen Field · Seattle, Washington'),
  (15, 'Arábia Saudita', 'Uruguai', '🇸🇦', '🇺🇾', 'Grupo H', '2026-06-16 02:00:00+04', 'Hard Rock Stadium · Miami Gardens, Florida'),
  (16, 'Irã', 'Nova Zelândia', '🇮🇷', '🇳🇿', 'Grupo G', '2026-06-16 05:00:00+04', 'SoFi Stadium · Inglewood, California'),
  (17, 'França', 'Senegal', '🇫🇷', '🇸🇳', 'Grupo I', '2026-06-16 23:00:00+04', 'MetLife Stadium · East Rutherford, New Jersey'),
  (18, 'Iraque', 'Noruega', '🇮🇶', '🇳🇴', 'Grupo I', '2026-06-17 02:00:00+04', 'Gillette Stadium · Foxborough, Massachusetts'),
  (19, 'Argentina', 'Argélia', '🇦🇷', '🇩🇿', 'Grupo J', '2026-06-17 05:00:00+04', 'GEHA Field at Arrowhead Stadium · Kansas City, Missouri'),
  (20, 'Áustria', 'Jordânia', '🇦🇹', '🇯🇴', 'Grupo J', '2026-06-17 08:00:00+04', 'Levi''s Stadium · Santa Clara, California'),
  (21, 'Portugal', 'RD Congo', '🇵🇹', '🇨🇩', 'Grupo K', '2026-06-17 21:00:00+04', 'NRG Stadium · Houston, Texas'),
  (22, 'Inglaterra', 'Croácia', '🏴', '🇭🇷', 'Grupo L', '2026-06-18 00:00:00+04', 'AT&T Stadium · Arlington, Texas'),
  (23, 'Gana', 'Panamá', '🇬🇭', '🇵🇦', 'Grupo L', '2026-06-18 03:00:00+04', 'BMO Field · Toronto'),
  (24, 'Uzbequistão', 'Colômbia', '🇺🇿', '🇨🇴', 'Grupo K', '2026-06-18 06:00:00+04', 'Estadio Banorte · Mexico City'),
  (25, 'Tchéquia', 'África do Sul', '🇨🇿', '🇿🇦', 'Grupo A', '2026-06-18 20:00:00+04', 'Mercedes-Benz Stadium · Atlanta, Georgia'),
  (26, 'Suíça', 'Bósnia e Herzegovina', '🇨🇭', '🇧🇦', 'Grupo B', '2026-06-18 23:00:00+04', 'SoFi Stadium · Inglewood, California'),
  (27, 'Canadá', 'Catar', '🇨🇦', '🇶🇦', 'Grupo B', '2026-06-19 02:00:00+04', 'BC Place · Vancouver'),
  (28, 'México', 'Coreia do Sul', '🇲🇽', '🇰🇷', 'Grupo A', '2026-06-19 05:00:00+04', 'Estadio Akron · Guadalajara'),
  (29, 'Estados Unidos', 'Austrália', '🇺🇸', '🇦🇺', 'Grupo D', '2026-06-19 23:00:00+04', 'Lumen Field · Seattle, Washington'),
  (30, 'Escócia', 'Marrocos', '🏴', '🇲🇦', 'Grupo C', '2026-06-20 02:00:00+04', 'Gillette Stadium · Foxborough, Massachusetts'),
  (31, 'Brasil', 'Haiti', '🇧🇷', '🇭🇹', 'Grupo C', '2026-06-20 04:30:00+04', 'Lincoln Financial Field · Philadelphia, Pennsylvania'),
  (32, 'Turquia', 'Paraguai', '🇹🇷', '🇵🇾', 'Grupo D', '2026-06-20 07:00:00+04', 'Levi''s Stadium · Santa Clara, California'),
  (33, 'Países Baixos', 'Suécia', '🇳🇱', '🇸🇪', 'Grupo F', '2026-06-20 21:00:00+04', 'NRG Stadium · Houston, Texas'),
  (34, 'Alemanha', 'Costa do Marfim', '🇩🇪', '🇨🇮', 'Grupo E', '2026-06-21 00:00:00+04', 'BMO Field · Toronto'),
  (35, 'Equador', 'Curaçao', '🇪🇨', '🇨🇼', 'Grupo E', '2026-06-21 04:00:00+04', 'GEHA Field at Arrowhead Stadium · Kansas City, Missouri'),
  (36, 'Tunísia', 'Japão', '🇹🇳', '🇯🇵', 'Grupo F', '2026-06-21 08:00:00+04', 'Estadio BBVA · Guadalupe'),
  (37, 'Espanha', 'Arábia Saudita', '🇪🇸', '🇸🇦', 'Grupo H', '2026-06-21 20:00:00+04', 'Mercedes-Benz Stadium · Atlanta, Georgia'),
  (38, 'Bélgica', 'Irã', '🇧🇪', '🇮🇷', 'Grupo G', '2026-06-21 23:00:00+04', 'SoFi Stadium · Inglewood, California'),
  (39, 'Uruguai', 'Cabo Verde', '🇺🇾', '🇨🇻', 'Grupo H', '2026-06-22 02:00:00+04', 'Hard Rock Stadium · Miami Gardens, Florida'),
  (40, 'Nova Zelândia', 'Egito', '🇳🇿', '🇪🇬', 'Grupo G', '2026-06-22 05:00:00+04', 'BC Place · Vancouver'),
  (41, 'Argentina', 'Áustria', '🇦🇷', '🇦🇹', 'Grupo J', '2026-06-22 21:00:00+04', 'AT&T Stadium · Arlington, Texas'),
  (42, 'França', 'Iraque', '🇫🇷', '🇮🇶', 'Grupo I', '2026-06-23 01:00:00+04', 'Lincoln Financial Field · Philadelphia, Pennsylvania'),
  (43, 'Noruega', 'Senegal', '🇳🇴', '🇸🇳', 'Grupo I', '2026-06-23 04:00:00+04', 'MetLife Stadium · East Rutherford, New Jersey'),
  (44, 'Jordânia', 'Argélia', '🇯🇴', '🇩🇿', 'Grupo J', '2026-06-23 07:00:00+04', 'Levi''s Stadium · Santa Clara, California'),
  (45, 'Portugal', 'Uzbequistão', '🇵🇹', '🇺🇿', 'Grupo K', '2026-06-23 21:00:00+04', 'NRG Stadium · Houston, Texas'),
  (46, 'Inglaterra', 'Gana', '🏴', '🇬🇭', 'Grupo L', '2026-06-24 00:00:00+04', 'Gillette Stadium · Foxborough, Massachusetts'),
  (47, 'Panamá', 'Croácia', '🇵🇦', '🇭🇷', 'Grupo L', '2026-06-24 03:00:00+04', 'BMO Field · Toronto'),
  (48, 'Colômbia', 'RD Congo', '🇨🇴', '🇨🇩', 'Grupo K', '2026-06-24 06:00:00+04', 'Estadio Akron · Guadalajara'),
  (49, 'Bósnia e Herzegovina', 'Catar', '🇧🇦', '🇶🇦', 'Grupo B', '2026-06-24 23:00:00+04', 'Lumen Field · Seattle, Washington'),
  (50, 'Suíça', 'Canadá', '🇨🇭', '🇨🇦', 'Grupo B', '2026-06-24 23:00:00+04', 'BC Place · Vancouver'),
  (51, 'Marrocos', 'Haiti', '🇲🇦', '🇭🇹', 'Grupo C', '2026-06-25 02:00:00+04', 'Mercedes-Benz Stadium · Atlanta, Georgia'),
  (52, 'Escócia', 'Brasil', '🏴', '🇧🇷', 'Grupo C', '2026-06-25 02:00:00+04', 'Hard Rock Stadium · Miami Gardens, Florida'),
  (53, 'Tchéquia', 'México', '🇨🇿', '🇲🇽', 'Grupo A', '2026-06-25 05:00:00+04', 'Estadio Banorte · Mexico City'),
  (54, 'África do Sul', 'Coreia do Sul', '🇿🇦', '🇰🇷', 'Grupo A', '2026-06-25 05:00:00+04', 'Estadio BBVA · Guadalupe'),
  (55, 'Curaçao', 'Costa do Marfim', '🇨🇼', '🇨🇮', 'Grupo E', '2026-06-26 00:00:00+04', 'Lincoln Financial Field · Philadelphia, Pennsylvania'),
  (56, 'Equador', 'Alemanha', '🇪🇨', '🇩🇪', 'Grupo E', '2026-06-26 00:00:00+04', 'MetLife Stadium · East Rutherford, New Jersey'),
  (57, 'Japão', 'Suécia', '🇯🇵', '🇸🇪', 'Grupo F', '2026-06-26 03:00:00+04', 'AT&T Stadium · Arlington, Texas'),
  (58, 'Tunísia', 'Países Baixos', '🇹🇳', '🇳🇱', 'Grupo F', '2026-06-26 03:00:00+04', 'GEHA Field at Arrowhead Stadium · Kansas City, Missouri'),
  (59, 'Paraguai', 'Austrália', '🇵🇾', '🇦🇺', 'Grupo D', '2026-06-26 06:00:00+04', 'Levi''s Stadium · Santa Clara, California'),
  (60, 'Turquia', 'Estados Unidos', '🇹🇷', '🇺🇸', 'Grupo D', '2026-06-26 06:00:00+04', 'SoFi Stadium · Inglewood, California'),
  (61, 'Noruega', 'França', '🇳🇴', '🇫🇷', 'Grupo I', '2026-06-26 23:00:00+04', 'Gillette Stadium · Foxborough, Massachusetts'),
  (62, 'Senegal', 'Iraque', '🇸🇳', '🇮🇶', 'Grupo I', '2026-06-26 23:00:00+04', 'BMO Field · Toronto'),
  (63, 'Cabo Verde', 'Arábia Saudita', '🇨🇻', '🇸🇦', 'Grupo H', '2026-06-27 04:00:00+04', 'NRG Stadium · Houston, Texas'),
  (64, 'Uruguai', 'Espanha', '🇺🇾', '🇪🇸', 'Grupo H', '2026-06-27 04:00:00+04', 'Estadio Akron · Guadalajara'),
  (65, 'Egito', 'Irã', '🇪🇬', '🇮🇷', 'Grupo G', '2026-06-27 07:00:00+04', 'Lumen Field · Seattle, Washington'),
  (66, 'Nova Zelândia', 'Bélgica', '🇳🇿', '🇧🇪', 'Grupo G', '2026-06-27 07:00:00+04', 'BC Place · Vancouver'),
  (67, 'Croácia', 'Gana', '🇭🇷', '🇬🇭', 'Grupo L', '2026-06-28 01:00:00+04', 'Lincoln Financial Field · Philadelphia, Pennsylvania'),
  (68, 'Panamá', 'Inglaterra', '🇵🇦', '🏴', 'Grupo L', '2026-06-28 01:00:00+04', 'MetLife Stadium · East Rutherford, New Jersey'),
  (69, 'Colômbia', 'Portugal', '🇨🇴', '🇵🇹', 'Grupo K', '2026-06-28 03:30:00+04', 'Hard Rock Stadium · Miami Gardens, Florida'),
  (70, 'RD Congo', 'Uzbequistão', '🇨🇩', '🇺🇿', 'Grupo K', '2026-06-28 03:30:00+04', 'Mercedes-Benz Stadium · Atlanta, Georgia'),
  (71, 'Argélia', 'Áustria', '🇩🇿', '🇦🇹', 'Grupo J', '2026-06-28 06:00:00+04', 'GEHA Field at Arrowhead Stadium · Kansas City, Missouri'),
  (72, 'Jordânia', 'Argentina', '🇯🇴', '🇦🇷', 'Grupo J', '2026-06-28 06:00:00+04', 'AT&T Stadium · Arlington, Texas');
